### ISSUE TITLE
Can't *npx dapp-store ini*t with *@solana-mobile/dapp-store-cli 0.5.2*

### ISSUE THREAD

**Issue by vofan** [solana-mobile/dapp-publishing#237]
```
$publishing % pnpm install --save-dev @solana-mobile/dapp-store-cli                   

devDependencies:
+ @solana-mobile/dapp-store-cli 0.5.2 <- ../packages/cli

Done in 1s
$publishing % npx dapp-store init
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module './packages/cli/lib/index.js' imported from./packages/cli/bin/dapp-store.js
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:226:11)
    at moduleResolve (node:internal/modules/esm/resolve:838:10)
    at defaultResolve (node:internal/modules/esm/resolve:1036:11)
    at DefaultModuleLoader.resolve (node:internal/modules/esm/loader:251:12)
    at DefaultModuleLoader.getModuleJob (node:internal/modules/esm/loader:140:32)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:33)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

Solution:

`pnpm install --save-dev @solana-mobile/dapp-store-cli@0.5.1`

**Comment by sdlaver** [comment]
@creativedrewy would you mind taking a look at this?

**Comment by creativedrewy** [comment]
Hey @vofan can you let me know what version of nodejs you're running?

**Comment by vofan** [comment]
Hello @creativedrewy.
```
% node --version
v20.5.1
```

**Comment by creativedrewy** [comment]
I just confirmed everything working with Node 18.16.0. Would you be able to use Node Version Manager and try Node 18?

**Comment by vofan** [comment]
yes, it works on 18.16**.0**, but not 18.16.1 and above

**Comment by creativedrewy** [comment]
Thanks for the update, and sorry about the troubles. I'm going to modify your title add add this bug to our backlog.
